import assert from 'node:assert/strict';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { database, migrate, transaction } from '../server/db.ts';
import { backup, restore } from '../server/backup.ts';
import { allocatePartner, allocateCustomerCode } from '../server/customer-code-store.ts';
import { localPostgres } from '../scripts/postgres-runtime.ts';

const root=path.join(os.tmpdir(),'autinberg-customer-code-test',randomUUID());
const secret=randomBytes(32).toString('hex');
const port=55589;
await mkdir(root,{recursive:true});
const pg=await localPostgres({databaseDir:path.join(root,'postgres'),port,user:'postgres',password:secret,persistent:true,onLog:()=>{},onError:()=>{}});
const pool=database(`postgresql://postgres:${secret}@127.0.0.1:${port}/codes_test`);
const restored=database(`postgresql://postgres:${secret}@127.0.0.1:${port}/codes_restore`);
let started=false;
try {
  await pg.initialise(); await pg.start(); started=true;
  await pg.createDatabase('codes_test'); await pg.createDatabase('codes_restore');
  await pool.query('CREATE ROLE anon'); await pool.query('CREATE ROLE authenticated');
  await migrate(pool); await migrate(pool); await migrate(restored);
  const user=randomUUID(), other=randomUUID();
  await pool.query("INSERT INTO users(id,name,email,password_hash,role) VALUES($1,'测试合伙人','codes@test.invalid','not-a-login-hash','sales'),($2,'另一位测试员工','codes2@test.invalid','not-a-login-hash','sales')",[user,other]);
  const partner=await allocatePartner(pool,{userId:user,joinYear:2026,name:'测试合伙人',market:'测试市场'});
  const same=await Promise.all(Array.from({length:12},()=>allocatePartner(pool,{userId:user,joinYear:2026,name:'测试合伙人',market:'测试市場'})));
  assert.equal(new Set(same.map(x=>x.id)).size,1);
  assert.equal(partner.partner_code,'A001');
  const partnerUsers=Array.from({length:20},()=>randomUUID());
  for(const id of partnerUsers) await pool.query("INSERT INTO users(id,name,email,password_hash,role) VALUES($1,'测试合伙人',$2,'not-a-login-hash','sales')",[id,id+'@test.invalid']);
  const partners=await Promise.all(partnerUsers.map(userId=>allocatePartner(pool,{userId,joinYear:2027,name:'测试合伙人',market:'测试市场'})));
  assert.equal(new Set(partners.map(p=>p.partner_code)).size,20);
  assert.equal((await pool.query('SELECT last_value FROM crm_partner_counters WHERE join_year=2027')).rows[0].last_value,20);
  const customer=async()=>{
    const id=randomUUID();
    await pool.query("INSERT INTO customers(id,owner_id,company,grade,stage,next_follow_up) VALUES($1,$2,'隔离测试客户','C','新询盘','2026-09-26')",[id,user]);
    return id;
  };
  const assign=(id:string,date='2026-09-26')=>allocateCustomerCode(pool,{customerId:id,partnerId:partner.id,firstContactDate:date,source:'new'});
  const ids=await Promise.all(Array.from({length:3},customer));
  const codes=[];
  for(const id of ids) codes.push(await assign(id));
  assert.deepEqual(codes,['A001260926001','A001260926002','A001260926003']);
  await pool.query('UPDATE customers SET deleted_at=now() WHERE id=$1',[ids[1]]);
  await pool.query('UPDATE customers SET owner_id=$2,data=$3 WHERE id=$1',[ids[0],other,JSON.stringify({phone:'+12025550199'})]);
  assert.deepEqual((await pool.query('SELECT crm_customer_code FROM customers WHERE id=ANY($1::uuid[]) ORDER BY crm_customer_code',[ids])).rows.map(x=>x.crm_customer_code),codes);
  assert.equal(await assign(await customer()),'A001260926004');
  const many=await Promise.all(Array.from({length:40},customer));
  const allocated=await Promise.all(many.map(id=>assign(id)));
  assert.equal(new Set(allocated).size,40);
  assert.ok(allocated.every(code=>/^[A-Z0-9]{13}$/.test(code)));
  assert.equal((await pool.query('SELECT last_value FROM crm_customer_code_counters WHERE partner_id=$1',[partner.id])).rows[0].last_value,44);
  const one=await customer();
  const repeats=await Promise.all(Array.from({length:12},()=>assign(one)));
  assert.equal(new Set(repeats).size,1);
  assert.equal(repeats[0],'A001260926045');
  await assert.rejects(pool.query("UPDATE customers SET crm_customer_code='A001260926888' WHERE id=$1",[one]),/终身固定/);
  await assert.rejects(pool.query('UPDATE customers SET crm_customer_code=NULL WHERE id=$1',[one]),/终身固定/);
  await assert.rejects(pool.query('DELETE FROM crm_customer_code_ledger WHERE customer_id=$1',[one]),/不可删除/);
  await assert.rejects(pool.query('UPDATE crm_customer_code_counters SET last_value=1 WHERE partner_id=$1',[partner.id]),/不可回退/);
  await assert.rejects(pool.query('DELETE FROM crm_partners WHERE id=$1',[partner.id]),/不可删除/);
  await assert.rejects(pool.query('UPDATE crm_partners SET user_id=$2 WHERE id=$1',[partner.id,other]),/不可修改/);
  const pending=await customer();
  await assert.rejects(pool.query("UPDATE customers SET crm_customer_code='A001260926777' WHERE id=$1",[pending]),/foreign key/);
  await assert.rejects(pool.query("INSERT INTO crm_customer_code_ledger(customer_id,code,partner_id,contact_date,assigned_sequence,source) VALUES($1,'A001260999777',$2,'2026-09-26',777,'new')",[pending,partner.id]),/不一致/);
  await assert.rejects(assign(pending,''),/首次接触日期/);
  assert.equal((await pool.query('SELECT crm_customer_code FROM customers WHERE id=$1',[pending])).rows[0].crm_customer_code,null);
  await pool.query("INSERT INTO crm_customer_code_counters(partner_id,contact_date,last_value) VALUES($1,'2026-09-27',999)",[partner.id]);
  await assert.rejects(assign(pending,'2026-09-27'),/999上限/);
  await assert.rejects(transaction(pool,async db=>{ await db.query('SET LOCAL ROLE anon'); await db.query('SELECT * FROM crm_customer_code_ledger'); }),/permission denied/);
  await assert.rejects(transaction(pool,async db=>{ await db.query('SET LOCAL ROLE authenticated'); await db.query("SELECT crm_allocate_customer_code($1,$2,'2026-09-26','new')",[pending,partner.id]); }),/permission denied/);
  const archive=await backup(pool);
  await restore(restored,archive);
  assert.equal((await restored.query('SELECT crm_customer_code FROM customers WHERE id=$1',[one])).rows[0].crm_customer_code,repeats[0]);
  assert.equal((await restored.query('SELECT count(*)::int AS n FROM crm_customer_code_ledger')).rows[0].n,45);
  await assert.rejects(restore(restored,archive),/不是空库/);
  const recovered=await allocateCustomerCode(restored,{customerId:pending,partnerId:partner.id,firstContactDate:'2026-09-26',source:'legacy_verified'});
  assert.equal(recovered,'A001260926046');
  console.log('PASS PostgreSQL: permanent codes, soft deletion, reassignment, 40 concurrent allocations, same-customer idempotency, exhaustion, immutable ledger, RLS, independent backup restore and next sequence');
  console.log('Test-only database; production untouched. Evidence directory:',root);
} finally {
  await pool.end(); await restored.end(); if(started) await pg.stop();
}
