import assert from 'node:assert/strict';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { database, migrate, transaction } from '../server/db.ts';
import { backup, restore } from '../server/backup.ts';
import { allocatePartner, allocateCustomerCode } from '../server/customer-code-store.ts';
import { localPostgres } from '../scripts/postgres-runtime.ts';
import { registerDocument, runtimeConfig } from '../server/document-registry.ts';
import { createApp } from '../server/app.ts';
import { hashPassword } from '../server/domain.ts';
import type { Server } from 'node:http';

const root=path.join(os.tmpdir(),'autinberg-customer-code-test',randomUUID());
const secret=randomBytes(32).toString('hex');
const port=55589;
await mkdir(root,{recursive:true});
const pg=await localPostgres({databaseDir:path.join(root,'postgres'),port,user:'postgres',password:secret,persistent:true,onLog:()=>{},onError:()=>{}});
const pool=database(`postgresql://postgres:${secret}@127.0.0.1:${port}/codes_test`);
const restored=database(`postgresql://postgres:${secret}@127.0.0.1:${port}/codes_restore`);
let started=false;
let http: Server | undefined;
try {
  await pg.initialise(); await pg.start(); started=true;
  await pg.createDatabase('codes_test'); await pg.createDatabase('codes_restore');
  await pool.query('CREATE ROLE anon'); await pool.query('CREATE ROLE authenticated');
  await migrate(pool); await migrate(pool); await migrate(restored);
  const user=randomUUID(), other=randomUUID();
  await pool.query("INSERT INTO users(id,name,email,password_hash,role) VALUES($1,'测试合伙人','codes@test.invalid','not-a-login-hash','sales'),($2,'另一位测试员工','codes2@test.invalid','not-a-login-hash','sales')",[user,other]);
  const partner=await allocatePartner(pool,{userId:user,joinYear:2026,name:'测试合伙人',market:'测试市场'});
  const same=await Promise.all(Array.from({length:12},()=>allocatePartner(pool,{userId:user,joinYear:2026,name:'测试合伙人',market:'测试市場'})));
  assert.equal(new Set(same.map(x=>x.id)).size,1);
  assert.equal(partner.partner_code,'A001');
  const partnerUsers=Array.from({length:20},()=>randomUUID());
  for(const id of partnerUsers) await pool.query("INSERT INTO users(id,name,email,password_hash,role) VALUES($1,'测试合伙人',$2,'not-a-login-hash','sales')",[id,id+'@test.invalid']);
  const partners=await Promise.all(partnerUsers.map(userId=>allocatePartner(pool,{userId,joinYear:2027,name:'测试合伙人',market:'测试市场'})));
  assert.equal(new Set(partners.map(p=>p.partner_code)).size,20);
  assert.equal((await pool.query('SELECT last_value FROM crm_partner_counters WHERE join_year=2027')).rows[0].last_value,20);
  const customer=async()=>{
    const id=randomUUID();
    await pool.query("INSERT INTO customers(id,owner_id,company,grade,stage,next_follow_up) VALUES($1,$2,'隔离测试客户','C','新询盘','2026-09-26')",[id,user]);
    return id;
  };
  const assign=(id:string,date='2026-09-26')=>allocateCustomerCode(pool,{customerId:id,partnerId:partner.id,firstContactDate:date,source:'new'});
  const ids=await Promise.all(Array.from({length:3},customer));
  const codes=[];
  for(const id of ids) codes.push(await assign(id));
  assert.deepEqual(codes,['A001260926001','A001260926002','A001260926003']);
  await pool.query('UPDATE customers SET deleted_at=now() WHERE id=$1',[ids[1]]);
  await pool.query('UPDATE customers SET owner_id=$2,data=$3 WHERE id=$1',[ids[0],other,JSON.stringify({phone:'+12025550199'})]);
  assert.deepEqual((await pool.query('SELECT crm_customer_code FROM customers WHERE id=ANY($1::uuid[]) ORDER BY crm_customer_code',[ids])).rows.map(x=>x.crm_customer_code),codes);
  assert.equal(await assign(await customer()),'A001260926004');
  const many=await Promise.all(Array.from({length:40},customer));
  const allocated=await Promise.all(many.map(id=>assign(id)));
  assert.equal(new Set(allocated).size,40);
  assert.ok(allocated.every(code=>/^[A-Z0-9]{13}$/.test(code)));
  assert.equal((await pool.query('SELECT last_value FROM crm_customer_code_counters WHERE partner_id=$1',[partner.id])).rows[0].last_value,44);
  const one=await customer();
  const repeats=await Promise.all(Array.from({length:12},()=>assign(one)));
  assert.equal(new Set(repeats).size,1);
  assert.equal(repeats[0],'A001260926045');
  await assert.rejects(pool.query("UPDATE customers SET crm_customer_code='A001260926888' WHERE id=$1",[one]),/终身固定/);
  await assert.rejects(pool.query('UPDATE customers SET crm_customer_code=NULL WHERE id=$1',[one]),/终身固定/);
  await assert.rejects(pool.query('DELETE FROM crm_customer_code_ledger WHERE customer_id=$1',[one]),/不可删除/);
  await assert.rejects(pool.query('UPDATE crm_customer_code_counters SET last_value=1 WHERE partner_id=$1',[partner.id]),/不可回退/);
  await assert.rejects(pool.query('DELETE FROM crm_partners WHERE id=$1',[partner.id]),/不可删除/);
  await assert.rejects(pool.query('UPDATE crm_partners SET user_id=$2 WHERE id=$1',[partner.id,other]),/不可修改/);
  const pending=await customer();
  await assert.rejects(pool.query("UPDATE customers SET crm_customer_code='A001260926777' WHERE id=$1",[pending]),/foreign key/);
  await assert.rejects(pool.query("INSERT INTO crm_customer_code_ledger(customer_id,code,partner_id,contact_date,assigned_sequence,source) VALUES($1,'A001260999777',$2,'2026-09-26',777,'new')",[pending,partner.id]),/不一致/);
  await assert.rejects(assign(pending,''),/首次接触日期/);
  assert.equal((await pool.query('SELECT crm_customer_code FROM customers WHERE id=$1',[pending])).rows[0].crm_customer_code,null);
  await pool.query("INSERT INTO crm_customer_code_counters(partner_id,contact_date,last_value) VALUES($1,'2026-09-27',999)",[partner.id]);
  await assert.rejects(assign(pending,'2026-09-27'),/999上限/);
  await assert.rejects(transaction(pool,async db=>{ await db.query('SET LOCAL ROLE anon'); await db.query('SELECT * FROM crm_customer_code_ledger'); }),/permission denied/);
  await assert.rejects(transaction(pool,async db=>{ await db.query('SET LOCAL ROLE authenticated'); await db.query("SELECT crm_allocate_customer_code($1,$2,'2026-09-26','new')",[pending,partner.id]); }),/permission denied/);
  let persisted=0;
  const documentInput={classCode:'QT',customerIds:[one],date:'2026-09-26',businessKind:'acceptance-isolated-quote',businessId:randomUUID(),requestKey:randomUUID(),actorId:user};
  const write=async()=>{persisted++;};
  const repeatedDocuments=await Promise.all(Array.from({length:20},()=>registerDocument(pool,documentInput,write)));
  assert.equal(new Set(repeatedDocuments.map(d=>d.doc_no)).size,1);
  assert.equal(persisted,1);
  assert.equal(repeatedDocuments[0].doc_no,'A001260926045-QT001');
  await assert.rejects(registerDocument(pool,{...documentInput,date:'2026-09-27'},write),/重复请求内容不一致/);
  const parallelDocuments=await Promise.all(Array.from({length:20},()=>registerDocument(pool,{...documentInput,businessId:randomUUID(),requestKey:randomUUID()},write)));
  assert.equal(new Set(parallelDocuments.map(d=>d.doc_no)).size,20);
  assert.equal((await pool.query('SELECT count(*)::int AS n FROM crm_document_registry')).rows[0].n,21);
  await assert.rejects(pool.query('DELETE FROM crm_document_registry WHERE id=$1',[repeatedDocuments[0].id]),/不可修改/);
  await assert.rejects(registerDocument(pool,{...documentInput,classCode:'AR',customerIds:[],businessId:randomUUID(),requestKey:randomUUID()},write),/必须关联一个客户/);
  const multi=await registerDocument(pool,{...documentInput,classCode:'PO',customerIds:[one,ids[0]],businessId:randomUUID(),requestKey:randomUUID()},write);
  assert.equal(multi.doc_no,'PO2609260001');
  for(const id of [one,ids[0]]) assert.equal((await pool.query('SELECT document_id FROM crm_document_customer_link WHERE customer_id=$1 AND document_id=$2',[id,multi.id])).rowCount,1);
  const failed={...documentInput,classCode:'CI',businessId:randomUUID(),requestKey:randomUUID()};
  await assert.rejects(registerDocument(pool,failed,async()=>{throw new Error('business insert rolled back');}),/rolled back/);
  assert.equal((await pool.query('SELECT 1 FROM crm_document_registry WHERE request_key=$1',[failed.requestKey])).rowCount,0);
  assert.equal((await registerDocument(pool,failed,write)).doc_no,'A001260926045-CI001');
  assert.equal((await runtimeConfig(pool)).sla_assign_minutes,30);
  await pool.query("UPDATE crm_runtime_config SET value='45' WHERE key='sla_assign_minutes'");
  assert.equal((await runtimeConfig(pool)).sla_assign_minutes,45);
  await assert.rejects(pool.query("UPDATE crm_runtime_config SET value='\"auto_reassign\"' WHERE key='escalation_after_breach'"),/check constraint/);
  await pool.query("UPDATE users SET role=CASE WHEN id=$1 THEN 'admin' ELSE role END,password_hash=$2 WHERE id=ANY($3::uuid[])",[user,await hashPassword(secret),[user,other]]);
  const origin='http://127.0.0.1:4691';
  http=await new Promise<Server>(resolve=>{const server=createApp(pool,{origin}).listen(4691,'127.0.0.1',()=>resolve(server));});
  async function login(email:string) {
    const response=await fetch(origin+'/api/auth/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({email,password:secret})});
    assert.equal(response.status,200);
    const data=await response.json() as {csrf:string};
    return {Cookie:response.headers.get('set-cookie')!.split(';')[0],'X-CSRF-Token':data.csrf,Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID()};
  }
  const adminHeaders=await login('codes@test.invalid'), salesHeaders=await login('codes2@test.invalid');
  // Isolated approved quotation fixture: exercise the real authenticated issue endpoint.
  const projectId=randomUUID(), quoteId=randomUUID();
  await pool.query('INSERT INTO quotation_projects(id,customer_id,name,created_by) VALUES($1,$2,$3,$4)',[projectId,one,'QT lifecycle isolated fixture',user]);
  await pool.query("INSERT INTO quotation_versions(id,project_id,number,input,snapshot,customer_snapshot,reason,created_by,status) VALUES($1,$2,1,'{}',$3,'{}','isolated approved fixture',$4,'approved')",[quoteId,projectId,JSON.stringify({issues:[],total:100,validThrough:'2099-12-31'}),user]);
  const issueHeaders={...adminHeaders,'Idempotency-Key':randomUUID()};
  const issueUrl=origin+'/api/quoting/versions/'+quoteId+'/issue';
  assert.equal((await fetch(issueUrl,{method:'POST',headers:salesHeaders,body:JSON.stringify({version:1})})).status,404);
  const issued=await Promise.all(Array.from({length:2},()=>fetch(issueUrl,{method:'POST',headers:issueHeaders,body:JSON.stringify({version:1})})));
  for(const response of issued) assert.equal(response.status,200);
  const firstIssue=await issued[0].json(); assert.deepEqual(await issued[1].json(),firstIssue);
  assert.equal(firstIssue.docNo,'A001260926045-QT022');
  assert.equal((await pool.query('SELECT biz_status FROM customers WHERE id=$1',[one])).rows[0].biz_status,'已报价');
  assert.equal((await pool.query('SELECT count(*)::int AS n FROM crm_customer_status_events WHERE customer_id=$1',[one])).rows[0].n,1);
  const transition=(await pool.query("SELECT details FROM audit_logs WHERE action='客户业务状态推进' AND entity_id=$1",[one])).rows[0].details;
  assert.equal(transition.trigger_doc_no,firstIssue.docNo);
  await assert.rejects(pool.query('UPDATE quotation_versions SET registered_document_id=NULL WHERE id=$1',[quoteId]),/不可更换/);
  const blockedQuote=randomUUID();
  await pool.query("INSERT INTO quotation_versions(id,project_id,number,input,snapshot,customer_snapshot,reason,created_by,status) VALUES($1,$2,2,'{}',$3,'{}','blocked fixture',$4,'approved')",[blockedQuote,projectId,JSON.stringify({issues:[],total:100,validThrough:'2099-12-31'}),user]);
  for(const state of ['已发货','已安装',null]) {
    // Test-only direct state fixture; no production state-edit endpoint is exposed.
    await pool.query('UPDATE customers SET biz_status=$2 WHERE id=$1',[one,state]);
    const r=await fetch(origin+'/api/quoting/versions/'+blockedQuote+'/issue',{method:'POST',headers:{...adminHeaders,'Idempotency-Key':randomUUID()},body:JSON.stringify({version:1})});
    assert.equal(r.status,409);
  }
  await pool.query("UPDATE customers SET biz_status='已报价' WHERE id=$1",[one]);
  assert.equal((await pool.query('SELECT registered_document_id FROM quotation_versions WHERE id=$1',[blockedQuote])).rows[0].registered_document_id,null);
  console.log('PASS real QT issue API: complete 资料 allowed, persistent QT number, customer advances once, trigger audit, duplicate request and unauthorized access, shipped/installed/unverified states blocked');
  assert.equal((await fetch(origin+'/api/settings/workflow',{headers:salesHeaders})).status,403);
  const config=await runtimeConfig(pool), changed={...config,sla_assign_minutes:30,sla_first_reply_minutes:31};
  assert.equal((await fetch(origin+'/api/settings/workflow',{method:'PUT',headers:salesHeaders,body:JSON.stringify(changed)})).status,403);
  for(let i=0;i<2;i++) assert.equal((await fetch(origin+'/api/settings/workflow',{method:'PUT',headers:adminHeaders,body:JSON.stringify(changed)})).status,200);
  assert.equal((await pool.query("SELECT count(*)::int AS n FROM audit_logs WHERE action='修改工作流时限'")).rows[0].n,1);
  assert.equal((await runtimeConfig(pool)).sla_first_reply_minutes,31);
  const audit=(await pool.query("SELECT details FROM audit_logs WHERE action='修改工作流时限'")).rows[0].details;
  assert.equal(audit.before.sla_assign_minutes,45); assert.equal(audit.after.sla_assign_minutes,30);
  await pool.query("UPDATE crm_runtime_config SET value='45' WHERE key='sla_assign_minutes'");
  const archive=await backup(pool);
  await restore(restored,archive);
  assert.equal((await restored.query('SELECT count(*)::int AS n FROM crm_document_registry')).rows[0].n,24);
  assert.equal((await restored.query('SELECT count(*)::int AS n FROM crm_customer_status_events')).rows[0].n,1);
  assert.equal((await runtimeConfig(restored)).sla_assign_minutes,45);
  assert.equal((await restored.query('SELECT crm_customer_code FROM customers WHERE id=$1',[one])).rows[0].crm_customer_code,repeats[0]);
  assert.equal((await restored.query('SELECT count(*)::int AS n FROM crm_customer_code_ledger')).rows[0].n,45);
  await assert.rejects(restore(restored,archive),/不是空库/);
  const recovered=await allocateCustomerCode(restored,{customerId:pending,partnerId:partner.id,firstContactDate:'2026-09-26',source:'legacy_verified'});
  assert.equal(recovered,'A001260926046');
  console.log('PASS PostgreSQL: permanent codes, soft deletion, reassignment, 40 concurrent allocations, same-customer idempotency, exhaustion, immutable ledger, RLS, independent backup restore and next sequence');
  console.log('Test-only database; production untouched. Evidence directory:',root);
  console.log('PASS document registry: original numbering module, 20 concurrent unique documents, 20 identical requests persist once, immutable issued numbers, B multi-customer FK lookup, AR association, atomic rollback, runtime config and restore');
} finally {
  if(http) await new Promise<void>((resolve,reject)=>http!.close(error=>error?reject(error):resolve()));
  await pool.end(); await restored.end(); if(started) await pg.stop();
}
