import assert from "node:assert/strict";
import {randomBytes,randomUUID} from "node:crypto";
import {mkdir,writeFile,readFile} from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import type {Server} from "node:http";
import {chromium,expect} from "@playwright/test";
import type {Browser} from "@playwright/test";
import {localPostgres} from "../scripts/postgres-runtime.ts";
import {database,migrate} from "../server/db.ts";
import {createApp} from "../server/app.ts";
import {hashPassword} from "../server/domain.ts";
import {backup,restore} from "../server/backup.ts";
import {fixtures} from "./quoting.fixtures.ts";
import {supplyScenario} from "./supply.scenario.ts";
import {catalogScenario} from "./catalog.scenario.ts";
import {catalogUi} from "./catalog.ui.ts";
import type {QuoteInput} from "../shared/quoting.ts";
import type {User} from "../shared/contracts.ts";

const runId=randomUUID(),password=randomBytes(24).toString("base64url"),dbPassword=randomBytes(24).toString("hex"),root=path.join(os.tmpdir(),"autinberg-quoting",runId),origin="http://127.0.0.1:4599";
const artifacts=process.env.ARTIFACT_DIR||path.join(root,"artifacts");await mkdir(artifacts,{recursive:true});
const postgres=await localPostgres({databaseDir:path.join(root,"postgres"),port:55579,user:"postgres",password:dbPassword,persistent:true,authMethod:"scram-sha-256",initdbFlags:["--encoding=UTF8","--locale=C"],postgresFlags:["-h","127.0.0.1"],onLog:()=>{},onError:()=>{}});
const url=`postgresql://postgres:${dbPassword}@127.0.0.1:55579/quoting_test`;
let pool=database(url),server:Server|undefined,browser:Browser|undefined,started=false;
type Agent={cookie:string;csrf:string;user:User};
async function request(a:Agent|null,urlPath:string,method="GET",body?:unknown,key:string=randomUUID()){
 const r=await fetch(origin+"/api"+urlPath,{method,headers:{Origin:origin,...(a?{Cookie:a.cookie,"X-CSRF-Token":a.csrf}:{}),...(body!==undefined?{"Content-Type":"application/json"}:{}),"Idempotency-Key":key},body:body!==undefined?JSON.stringify(body):undefined});
 const data=r.headers.get("content-type")?.includes("application/json")?await r.json():Buffer.from(await r.arrayBuffer());return{status:r.status,data,cookie:r.headers.get("set-cookie")};
}
async function ok(a:Agent|null,u:string,m="GET",b?:unknown,key?:string){const r=await request(a,u,m,b,key);assert.equal(r.status,200,`${m} ${u}: ${JSON.stringify(r.data)}`);return r.data;}
async function login(email:string):Promise<Agent>{const r=await request(null,"/auth/login","POST",{email,password});assert.equal(r.status,200);return{cookie:r.cookie!.split(";")[0],csrf:r.data.csrf,user:r.data.user};}
async function start(){server=createApp(pool,{origin,serveStatic:true}).listen(4599,"127.0.0.1");await new Promise<void>((resolve,reject)=>{server!.once("listening",resolve);server!.once("error",reject);});}
async function close(){await new Promise<void>((resolve,reject)=>server?server.close(e=>e?reject(e):resolve()):resolve());server=undefined;}
const passed:string[]=[];const pass=(s:string)=>{passed.push(s);console.log("PASS "+s);};
try{
await postgres.initialise();await postgres.start();started=true;await postgres.createDatabase("quoting_test");await pool.query("CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN;");await migrate(pool);
 const adminId=randomUUID();await pool.query("INSERT INTO users(id,name,email,password_hash,role) VALUES($1,'测试管理员','admin@test.invalid',$2,'admin')",[adminId,await hashPassword(password)]);await start();
 const admin=await login("admin@test.invalid");
 const dataApi=await pool.connect();
 try {
  assert.equal((await dataApi.query("SELECT has_table_privilege('anon','public.users','select') AS allowed")).rows[0].allowed,false);
  assert.equal((await dataApi.query("SELECT has_table_privilege('authenticated','public.customers','select') AS allowed")).rows[0].allowed,false);
  assert.equal((await dataApi.query("SELECT has_table_privilege('anon','public.factory_product_images','select') AS allowed")).rows[0].allowed,false);
  await dataApi.query("BEGIN");
  await dataApi.query("GRANT USAGE ON SCHEMA public TO anon");
  await dataApi.query("GRANT SELECT ON public.users TO anon");
  await dataApi.query("SET LOCAL ROLE anon");
  assert.equal((await dataApi.query("SELECT count(*)::int AS total FROM users")).rows[0].total,0);
 } finally {await dataApi.query("ROLLBACK");dataApi.release();}
 pass("数据库匿名/前端认证角色无CRM表权限，即使误授予SELECT仍被RLS默认拒绝");
 for(const[name,role]of [["a","sales"],["b","sales"],["logistics","logistics"],["technical","technical"]])await ok(admin,"/team","POST",{name,email:`${name}@test.invalid`,role,password});
 const a=await login("a@test.invalid"),b=await login("b@test.invalid"),log=await login("logistics@test.invalid"),tech=await login("technical@test.invalid");
 const ca=await ok(admin,"/customers","POST",{company:"TEST Alpha",contact:"Test A",country:"UAE",grade:"A",ownerId:a.user.id}),cb=await ok(admin,"/customers","POST",{company:"TEST Beta Private",contact:"Test B",country:"UK",grade:"B",ownerId:b.user.id});
 const fixture=fixtures();await ok(admin,"/quoting/settings","PUT",{data:fixture.settings,version:1});
 fixture.product.id=(await ok(admin,"/quoting/products","POST",fixture.product)).id;fixture.freight.id=(await ok(admin,"/quoting/freight","POST",fixture.freight)).id;fixture.input.lines[0].productId=fixture.product.id;fixture.input.freightId=fixture.freight.id;
 const catalog=await ok(a,"/quoting/products");assert.ok(!JSON.stringify(catalog).includes('"cost"'));assert.ok(!JSON.stringify(catalog).includes('"internal"'));
 assert.equal((await request(a,"/quoting/settings","PUT",{data:fixture.settings,version:2})).status,403);assert.equal((await request(tech,"/customers")).status,403);assert.equal((await request(log,"/whatsapp/chats")).status,403);pass("真实独立账号、角色隔离与销售成本脱敏");
 const projectA=(await ok(a,"/quoting/projects","POST",{customerId:ca.id,name:"TEST Dubai villa"})).id,projectB=(await ok(b,"/quoting/projects","POST",{customerId:cb.id,name:"Private"})).id;
 assert.equal((await request(a,`/quoting/projects/${projectB}`)).status,404);assert.equal((await request(a,`/quoting/projects/${projectB}/preview`,"POST",fixture.input)).status,404);assert.equal((await ok(a,"/quoting/projects")).total,1);pass("销售A不能猜测ID读取销售B项目、搜索或预览");
 async function save(projectId:string,input:QuoteInput,actor=a){const p=await ok(actor,`/quoting/projects/${projectId}`);return(await ok(actor,`/quoting/projects/${projectId}/versions`,"POST",{baseVersion:p.project.version,input,reason:"TEST version"})).id as string;}
 async function get(q:string){return ok(a,`/quoting/versions/${q}`);}
 const v1=await save(projectA,fixture.input),quote1=await get(v1);assert.equal(quote1.snapshot.total,700.62);assert.equal(quote1.snapshot.cbm,1.89);assert.ok(!JSON.stringify(quote1).includes("costCny"));
 assert.equal((await request(a,`/quoting/projects/${projectA}/versions`,"POST",{baseVersion:1,input:fixture.input,reason:"stale"})).status,409);
 await assert.rejects(pool.query("UPDATE quotation_versions SET input='{}' WHERE id=$1",[v1]),/immutable/);pass("标准3樘推拉门真实保存、后端计价、并发冲突与数据库快照不可覆盖");
 await ok(a,`/quoting/versions/${v1}/submit`,"POST",{version:quote1.version});await ok(a,`/quoting/versions/${v1}/issue`,"POST",{version:(await get(v1)).version});
 const en=(await ok(a,`/quoting/versions/${v1}/documents`,"POST",{kind:"quotation",language:"en"})).id;
 const both=(await ok(a,`/quoting/versions/${v1}/documents`,"POST",{kind:"quotation",language:"both"})).id;
 const pdf=await ok(a,`/quoting/documents/${en}`);assert.ok(pdf.subarray(0,5).toString()==="%PDF-");assert.equal((await request(b,`/quoting/documents/${en}`)).status,404);
 await writeFile(path.join(artifacts,"quotation-en.pdf"),pdf);await writeFile(path.join(artifacts,"quotation-bilingual.pdf"),await ok(a,`/quoting/documents/${both}`));
 const same=(await ok(a,`/quoting/versions/${v1}/documents`,"POST",{kind:"quotation",language:"en"})).id;assert.equal(same,en);pass("正式中英PDF生成、权限下载、数据库持久化与重复生成不变");
 const low=structuredClone(fixture.input);low.lines[0].unitPrice=1;low.lines[0].discountPct=30;
 const lowProject=(await ok(a,"/quoting/projects","POST",{customerId:ca.id,name:"LOW TEST"})).id,lowV=await save(lowProject,low);await ok(a,`/quoting/versions/${lowV}/submit`,"POST",{version:1});assert.equal((await request(a,`/quoting/versions/${lowV}/issue`,"POST",{version:2})).status,422);
 const tasks=await ok(admin,"/quoting/tasks");const adminTask=tasks.find((t:{quote_id:string;discipline:string})=>t.quote_id===lowV&&t.discipline==="admin");assert.equal((await request(a,`/quoting/tasks/${adminTask.id}/review`,"POST",{version:1,status:"approved",comment:"bypass"})).status,404);await ok(admin,`/quoting/tasks/${adminTask.id}/review`,"POST",{version:1,status:"approved",comment:"TEST admin approved special commercial exception"});await ok(a,`/quoting/versions/${lowV}/issue`,"POST",{version:(await get(lowV)).version});pass("客户端手动低价与超限折扣不能跳过管理员审批");
 const missing=structuredClone(fixture.input);missing.incoterm="DDP";const missingV=await save(lowProject,missing);await ok(a,`/quoting/versions/${missingV}/submit`,"POST",{version:1});const mt=(await ok(admin,"/quoting/tasks")).find((t:{quote_id:string;discipline:string})=>t.quote_id===missingV&&t.discipline==="logistics");await ok(admin,`/quoting/tasks/${mt.id}/assign`,"POST",{version:1,userId:log.user.id});assert.equal((await request(log,`/quoting/tasks/${mt.id}/review`,"POST",{version:2,status:"approved",comment:"Cannot waive missing duty"})).status,422);pass("DDP缺少税费/清关时物流审核也无法绕过");
 const special=structuredClone(fixture.input);special.lines[0].nonstandard=true;special.lines[0].special="TEST irregular design";const specialV=await save(lowProject,special);await ok(a,`/quoting/versions/${specialV}/submit`,"POST",{version:1});const st=(await ok(admin,"/quoting/tasks")).find((t:{quote_id:string;discipline:string})=>t.quote_id===specialV&&t.discipline==="technical");assert.equal((await request(tech,`/quoting/tasks/${st.id}`)).status,404);await ok(admin,`/quoting/tasks/${st.id}/assign`,"POST",{version:1,userId:tech.user.id});const taskView=await ok(tech,`/quoting/tasks/${st.id}`);assert.ok(!JSON.stringify(taskView).includes("unitPrice"));assert.equal((await request(tech,`/quoting/tasks/${st.id}/review`,"POST",{version:2,status:"approved",comment:"missing drawing"})).status,422);
 const file=(await ok(tech,`/quoting/projects/${lowProject}/files`,"POST",{name:"TEST drawing.pdf",mime:"application/pdf",data:pdf.toString("base64"),kind:"technical",taskId:st.id})).id;assert.equal((await request(b,`/quoting/files/${file}`)).status,404);await ok(tech,`/quoting/tasks/${st.id}/review`,"POST",{version:2,status:"approved",comment:"TEST technical reviewed",fileId:file});pass("技术任务按分配授权、隐藏金额、强制图纸附件及跨员工附件隔离");
 await ok(admin,"/quoting/products/"+fixture.product.id,"PUT",{...fixture.product,prices:{...fixture.product.prices,guide:500},version:1});await ok(admin,"/quoting/settings","PUT",{data:{...fixture.settings,fx:{USD:{...fixture.settings.fx.USD,cnyPerUnit:8}}},version:2});assert.equal((await get(v1)).snapshot.total,700.62);assert.deepEqual(await ok(a,`/quoting/documents/${en}`),pdf);pass("修改底价和汇率不改变历史报价或历史PDF");
 const confirmKey=randomUUID(),body={version:(await get(v1)).version,contact:"TEST Buyer",evidence:"TEST customer confirmed by email, evidence reviewed"};const order=await ok(a,`/quoting/versions/${v1}/confirm`,"POST",body,confirmKey);assert.deepEqual(await ok(a,`/quoting/versions/${v1}/confirm`,"POST",body,confirmKey),order);
 const pi=(await ok(a,`/quoting/versions/${v1}/documents`,"POST",{kind:"pi",language:"both"})).id,contract=(await ok(a,`/quoting/versions/${v1}/documents`,"POST",{kind:"contract",language:"both"})).id;await writeFile(path.join(artifacts,"pi.pdf"),await ok(a,`/quoting/documents/${pi}`));await writeFile(path.join(artifacts,"contract-draft.pdf"),await ok(a,`/quoting/documents/${contract}`));assert.equal((await request(a,`/quoting/projects/${projectA}/versions`,"POST",{baseVersion:2,input:fixture.input,reason:"illegal edit"})).status,409);pass("客户确认生成唯一订单、生产任务、PI和明确草稿合同");
 const factoryA=(await ok(admin,"/supply/factories","POST",{name:"TEST 工厂A",contact:{person:"A",phone:"",email:""}})).id,factoryB=(await ok(admin,"/supply/factories","POST",{name:"TEST 工厂B",contact:{person:"B",phone:"",email:""}})).id;
 await ok(admin,`/supply/factories/${factoryA}/invite`,"POST",{name:"工厂A",email:"factory-a@test.invalid",password});await ok(admin,`/supply/factories/${factoryB}/invite`,"POST",{name:"工厂B",email:"factory-b@test.invalid",password});
 const fa=await login("factory-a@test.invalid"),fb=await login("factory-b@test.invalid");assert.equal((await request(fa,"/customers")).status,403);assert.equal((await request(fa,"/quoting/products")).status,403);
 const fp=(await ok(fa,"/supply/factory-products","POST",{sku:"FACTORY-A-DOOR",nameZh:"工厂A测试门",nameEn:"Factory A Test Door",category:"推拉门",series:"FA",specification:"TEST 2.0mm profile",imageUrls:[],supplyPrice:1000,currency:"CNY",pricingMethod:"area_options",pricingRule:fixture.product,leadDays:25})).id;
 assert.equal((await ok(fb,"/supply/factory-products")).length,0);let fpRow=(await ok(fa,"/supply/factory-products"))[0];await ok(fa,`/supply/factory-products/${fp}/submit`,"POST",{version:fpRow.version});fpRow=(await ok(admin,"/supply/factory-products")).find((p:{id:string})=>p.id===fp);await ok(admin,`/supply/factory-products/${fp}/review`,"POST",{status:"approved",note:"TEST approved",guidePrice:1500,minimumPrice:1200,retailPrice:1800,active:true,commercial:{packingSale:140},version:fpRow.version});const salesCatalog=await ok(a,"/quoting/products");assert.ok(salesCatalog.some((p:{sku:string})=>p.sku==="FACTORY-A-DOOR"));assert.ok(!JSON.stringify(salesCatalog).includes('"factory":1000'));pass("工厂A/B独立账号、产品与供货价隔离、公司审核后发布销售目录");
 const salesOrders=await ok(admin,"/supply/orders"),salesOrder=salesOrders.find((o:{company:string})=>o.company==="TEST Alpha");assert.ok(salesOrder);assert.equal((await ok(b,"/supply/orders")).length,0);const salesDetail=await ok(admin,`/supply/orders/${salesOrder.id}`),purchase=(await ok(admin,`/supply/orders/${salesOrder.id}/purchase-orders`,"POST",{factoryId:factoryA,itemIds:[salesDetail.items[0].id],promisedDate:null})).id;
 assert.equal((await ok(fa,"/supply/purchase-orders")).length,1);assert.equal((await ok(fb,"/supply/purchase-orders")).length,0);assert.equal((await request(fb,`/supply/purchase-orders/${purchase}`)).status,404);assert.equal((await request(b,`/supply/purchase-orders/${purchase}`)).status,404);let purchaseView=await ok(fa,`/supply/purchase-orders/${purchase}`);await ok(fa,`/supply/purchase-orders/${purchase}/confirm`,"POST",{price:3000,promisedDate:"2027-01-30",note:"TEST accepted",version:purchaseView.order.version});await ok(fa,`/supply/purchase-orders/${purchase}/updates`,"POST",{stage:"materials",plannedAt:null,actualAt:new Date().toISOString(),quantity:3,note:"TEST materials arrived"});assert.equal((await request(fb,`/supply/purchase-orders/${purchase}/updates`,"POST",{stage:"assembly",plannedAt:null,actualAt:new Date().toISOString(),quantity:3,note:"intrusion"})).status,404);purchaseView=await ok(admin,`/supply/purchase-orders/${purchase}`);assert.equal(purchaseView.order.status,"accepted");assert.equal(purchaseView.updates[0].note,"TEST materials arrived");pass("销售A/B与工厂A/B订单隔离、工厂确认价格交期并反馈生产节点");
 await catalogScenario({ok,request,admin,a,fa,fb,fixture,pass});
 await supplyScenario({ok,request,login,admin,a,b,fa,fb,customerId:ca.id,factoryId:factoryA,password,fixture,pass});
const blank=await readFile(path.resolve("public/templates/quotation-lines.xlsx"));const imported=await ok(a,"/quoting/import-lines","POST",{data:blank.toString("base64")});assert.equal(imported.lines.length,0);assert.equal((await request(a,"/quoting/import-lines","POST",{data:Buffer.from("bad zip").toString("base64")})).status,400);pass("Excel空白模板可读取，损坏文件被拒绝");
 const mobileProject=(await ok(a,"/quoting/projects","POST",{customerId:ca.id,name:"Mobile TEST"})).id;
 // Automated regression harness; supplement new interaction checks in the in-app browser when available.
 browser=await chromium.launch({channel:process.platform==="win32"?"msedge":undefined,headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 await page.goto(origin+"/login");await page.getByLabel("邮箱",{exact:true}).fill("a@test.invalid");await page.getByLabel("密码",{exact:true}).fill(password);await page.getByRole("button",{name:"登录",exact:true}).click();await page.getByRole("link",{name:"报价管理",exact:true}).click();await expect(page.getByText("奥汀堡海外产品出图报价系统",{exact:true})).toBeVisible();await page.getByLabel("搜索项目或客户").fill("Dubai");await page.locator(`a[href="/quotations/${projectA}"]`).first().click();await expect(page.getByText("USD 700.62",{exact:true})).toBeVisible();await expect(page.locator("svg")).toHaveCount(1);await page.screenshot({path:path.join(artifacts,"desktop.png"),fullPage:false});
 const factoryPage=await browser.newPage({viewport:{width:1280,height:900}});factoryPage.on("pageerror",e=>errors.push(e.message));await factoryPage.goto(origin+"/login");await factoryPage.getByLabel("邮箱",{exact:true}).fill("factory-a@test.invalid");await factoryPage.getByLabel("密码",{exact:true}).fill(password);await factoryPage.getByRole("button",{name:"登录",exact:true}).click();await expect(factoryPage.getByRole("link",{name:"供货产品",exact:true})).toBeVisible();await expect(factoryPage.getByRole("link",{name:"客户管理",exact:true})).toHaveCount(0);await expect(factoryPage.getByText("FACTORY-A-DOOR",{exact:false})).toBeVisible();await factoryPage.getByRole("link",{name:"工厂订单",exact:true}).click();await expect(factoryPage.getByText(purchaseView.order.order_number,{exact:true})).toBeVisible();await factoryPage.screenshot({path:path.join(artifacts,"factory-portal.png"),fullPage:false});
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on("pageerror",e=>errors.push(e.message));await mobile.goto(origin+"/login");await mobile.getByLabel("邮箱",{exact:true}).fill("a@test.invalid");await mobile.getByLabel("密码",{exact:true}).fill(password);await mobile.getByRole("button",{name:"登录",exact:true}).click();await mobile.waitForURL(url=>url.pathname!=="/login");await mobile.goto(`${origin}/quotations/${mobileProject}`);await mobile.getByLabel("国家",{exact:true}).fill("UAE");await mobile.getByLabel("贸易条款指定地点").fill("TEST Foshan");await mobile.getByLabel("付款条款",{exact:true}).fill("TEST terms");await mobile.getByRole("button",{name:"＋ TEST-SLIDE · 测试推拉门",exact:true}).click();await mobile.getByLabel("宽度",{exact:true}).fill("2000");await mobile.getByLabel("高度",{exact:true}).fill("2400");await mobile.getByRole("button",{name:"保存 V1 草稿",exact:true}).click();await expect(mobile.getByText("保存版本 V1 · 草稿",{exact:true})).toBeVisible();await mobile.screenshot({path:path.join(artifacts,"mobile.png"),fullPage:false});assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));assert.deepEqual(errors,[]);pass("桌面、工厂门户和390px手机：登录、隔离菜单、多参数编辑与保存，未见运行错误或横向溢出");
 await catalogUi(browser,origin,password,artifacts);pass("真实工厂UI录入尺寸/档位/选配/包装、上传图片、编辑保存、公司独立定价审核、修订及390px编辑回归");
 await browser.close();browser=undefined;await close();await pool.end();await postgres.stop();await postgres.start();pool=database(url);await start();assert.equal((await get(v1)).snapshot.total,700.62);assert.deepEqual(await ok(a,`/quoting/documents/${en}`),pdf);pass("重启应用与PostgreSQL后报价、会话及PDF内容保持");
 const archive=await backup(pool);await postgres.createDatabase("quoting_restore");const restored=database(url.replace("quoting_test","quoting_restore"));await migrate(restored);const counts=await restore(restored,archive);assert.equal(counts.quotation_documents,4);assert.equal(counts.factory_product_images,3);assert.deepEqual((await restored.query("SELECT id,sha256,bytes_base64 FROM factory_product_images ORDER BY id")).rows,(await pool.query("SELECT id,sha256,bytes_base64 FROM factory_product_images ORDER BY id")).rows);assert.equal((await restored.query("SELECT bytes_base64 FROM quotation_documents WHERE id=$1",[en])).rows[0].bytes_base64,pdf.toString("base64"));await assert.rejects(restore(restored,archive),/不是空库/);await restored.end();pass("独立空数据库恢复报价、订单、审批及4份PDF，拒绝覆盖非空库");
 await ok(admin,`/team/${a.user.id}`,"PUT",{name:a.user.name,email:a.user.email,role:"sales",active:false,version:1});assert.equal((await request(a,`/quoting/documents/${en}`)).status,401);pass("停用员工后旧会话不能访问报价或PDF");
 await writeFile(path.join(artifacts,"results.json"),JSON.stringify({passed,artifacts},null,2));console.log(`QUOTING QA: ${passed.length} groups passed. Artifacts: ${artifacts}`);
}finally{await browser?.close();await close();await pool.end();if(started)await postgres.stop();}
