import test from "node:test";
import assert from "node:assert/strict";
import { calculate, policy, publicCalculation } from "../server/quoting/engine.ts";
import { fixtures,today } from "./quoting.fixtures.ts";
import { quoteInputSchema } from "../shared/quoting.ts";
function calc(){const f=fixtures();return{...f,run:()=>calculate(f.input,[f.product],f.freight,f.settings,policy(f.settings,{id:"test",role:"sales"}),today,"project")};}
test("3 test sliding doors: area, package, weight, freight, decimal total",()=>{const f=calc(),c=f.run();assert.equal(c.productTotal,600);assert.equal(c.packingTotal,58.33);assert.equal(c.cbm,1.89);assert.equal(c.grossKg,303);assert.equal(c.freightTotal,42.29);assert.equal(c.total,700.62);assert.deepEqual(c.issues,[]);});
test("mm/cm/m equivalent and minimum billing area",()=>{const f=calc(),base=f.run().total;f.input.lines[0].unit="cm";f.input.lines[0].width=200;f.input.lines[0].height=240;assert.equal(f.run().total,base);f.input.lines[0].unit="m";f.input.lines[0].width=2;f.input.lines[0].height=2.4;assert.equal(f.run().total,base);f.product.minArea=6;assert.equal(f.run().lines[0].billedArea,6);});
test("missing, expired and mismatched freight cannot become zero",()=>{const f=calc();f.freight.validUntil="2020-01-01";assert.equal(f.run().total,null);f.freight.validUntil=f.input.validUntil;f.freight.country="UK";assert.equal(f.run().freightTotal,null);});
test("DDP duties, clearance and destination coverage mandatory",()=>{const f=calc();f.input.incoterm="DDP";assert.ok(f.run().issues.some(i=>i.code==="coverage"&&i.hard));f.input.customerForwarder=true;assert.ok(f.run().issues.some(i=>i.code==="forwarder"));});
test("EXW excludes freight; FCA requires configured scope",()=>{const f=calc();f.input.incoterm="EXW";assert.equal(f.run().freightTotal,0);f.input.incoterm="FCA";assert.ok(f.run().issues.some(i=>i.code==="fca"));});
test("tampered totals ignored; manual price/discount/floor cannot bypass approval",()=>{const f=calc();Object.assign(f.input,quoteInputSchema.parse({...f.input,total:1,cost:0}));assert.equal(f.run().total,700.62);f.input.lines[0].unitPrice=1;f.input.lines[0].discountPct=20;const c=f.run();for(const code of ["override","discount","minimum","margin"])assert.ok(c.issues.some(i=>i.code===code),code);});
test("unknown dimensions/specs and options require checks",()=>{const f=calc();f.input.lines[0].width=11000;f.input.lines[0].options=["unknown"];f.input.lines[0].specs.glass="different";const c=f.run();for(const code of ["nonstandard","nonstandard-price","options","specification"])assert.ok(c.issues.some(i=>i.code===code));});
test("SVG responds to width, grids and opening, escapes untrusted strings",()=>{const f=calc(),a=f.run().lines[0].svg;f.input.lines[0].width=2500;f.input.lines[0].columns=3;f.input.lines[0].panels=["left","fixed","right"];f.input.lines[0].swing="out";f.product.sku='"><script>alert(1)</script>';const b=f.run().lines[0].svg;assert.notEqual(a,b);assert.ok(b.includes("2500 mm")&&b.includes("NOT FOR PRODUCTION"));assert.ok(!b.includes("<script>"));});
test("no private costs or settings serialized for ordinary sales",()=>{const f=calc(),p=policy(f.settings,{id:"test",role:"sales"}),c=f.run(),publicC=publicCalculation(c,p);const text=JSON.stringify(publicC);for(const word of ['"private"','costCny','marginPct','"settings"','"internal"'])assert.ok(!text.includes(word),word);const allowed=publicCalculation(c,{...p,viewCosts:true});assert.ok(allowed.costs);assert.ok(!JSON.stringify(allowed).includes('"policies"'));});
test("pricing methods use configured basis, bands and material formula",()=>{const f=calc();f.input.incoterm="EXW";f.input.currency="CNY";for(const method of ["unit","set","piece"] as const){f.product.pricing=method;assert.equal(f.run().productTotal,900);}f.product.pricing="linear";assert.equal(f.run().productTotal,7920);f.product.pricing="fixed";assert.equal(f.run().productTotal,300);f.product.pricing="range";f.product.bands=[{maxArea:4.8,cost:100,sale:900}];assert.equal(f.run().productTotal,2700);f.product.pricing="composite";f.product.formula=[{name:"test area",basis:"area",coefficient:2,cost:50,sale:100}];assert.equal(f.run().productTotal,2880);});
test("missing FX and packing config are hard blocks",()=>{const f=calc();f.settings.fx={};f.product.packing.configured=false;assert.ok(f.run().issues.some(i=>i.code==="fx"&&i.hard));assert.ok(f.run().issues.some(i=>i.code==="packing"&&i.hard));});
