import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useSession} from './context.tsx';
import {useMutation,useResource} from './api.ts';
import {ErrorBox,Field,Loading,Panel} from './ui.tsx';
import {feeNames,unitNames,type PricingConfig} from '../../shared/pricing.ts';
type Rate={currency:string;cnyPerUnit:number;date:string;validUntil:string;source:string;sourceUrl?:string;status:string;firstSyncedAt?:string;bufferPct?:number;syncFailed?:boolean};
type Overview={reference:Rate[];company:Rate[];missingCurrencies:string[];config:PricingConfig;configVersion:number;lastChecked:string|null;lastSuccess:string|null;lastError:string|null;lastHeartbeat:string|null;nextRun:string;running:boolean;runs:{id:string;trigger:string;started_at:string;status:string;attempts:number;error:string|null}[];alerts:{id:string;message:string}[]};
type Meta={id:string;version:number;currency:string;source:string;method:string;sourceDate:string|null;lastSuccess:string|null;validFrom:string|null;validUntil:string|null;status:string};
type ProductRow=Meta&{sku:string;name:string;category:string;series:string;specs:Record<string,string>;width:number[];height:number[];packing:string;pricing:string;sale:number|null;options:{name:string;sale:number|null;basis:string}[]};
type FreightRow=Meta&{name:string;country:string;city:string;originPort:string;destinationPort:string;mode:string;container:string;inclusions:string;exclusions:string;transitDays:string;limits:{minCbm:number|null;maxCbm:number|null;minKg:number|null;maxKg:number|null}|null;costRestricted:boolean;fees:{kind:string;basis:string;rate:number|null;minimum:number|null}[]};
const time=(v:string|null|undefined)=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'尚无记录';
const statusClass=(s:string)=>s==='有效'?'price-valid':s==='已过期'?'price-expired':'price-pending';
const Badge=({s}:{s:string})=><span className={`price-badge ${statusClass(s)}`}>{s}</span>;
function Provenance({p}:{p:Meta}) {return <><td>{p.source}<small>{p.method}</small></td><td>{p.sourceDate||'来源日期待补'}<small>最近成功：{p.lastSuccess?time(p.lastSuccess):'未同步'}</small></td><td>{p.validFrom||'未确认'} 至 {p.validUntil||'未确认'}<small>版本 {p.version}</small></td><td><Badge s={p.status}/></td></>;}
export default function DailyPrices() {
 const {user,revision}=useSession(),[tab,setTab]=useState('fx'),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[filters,setFilters]=useState({country:'',city:'',origin:'',destination:'',mode:'',container:'',cbm:'',kg:'',date:''});
 const overview=useResource<Overview>('/pricing/overview',revision,15000),catalog=useResource<{products:ProductRow[];freight:FreightRow[]}>('/pricing/catalog',revision);
 if(overview.loading||catalog.loading)return <Loading/>;
 if(!overview.data||!catalog.data)return <ErrorBox message={overview.error||catalog.error}/>;
 const o=overview.data,c=catalog.data,q=search.trim().toLowerCase();
 const products=c.products.filter(p=>(!q||`${p.sku} ${p.name} ${p.category} ${p.series} ${JSON.stringify(p.specs)}`.toLowerCase().includes(q))&&(!status||p.status===status));
 const freight=c.freight.filter(p=>(!q||`${p.name} ${p.source} ${p.country} ${p.city} ${p.originPort} ${p.destinationPort}`.toLowerCase().includes(q))&&(!status||p.status===status)&&(!filters.country||p.country.toLowerCase().includes(filters.country.toLowerCase()))&&(!filters.city||p.city.toLowerCase().includes(filters.city.toLowerCase()))&&(!filters.origin||p.originPort.includes(filters.origin))&&(!filters.destination||p.destinationPort.includes(filters.destination))&&(!filters.mode||p.mode===filters.mode)&&(!filters.container||p.container.includes(filters.container))&&(!filters.date||(!!p.validFrom&&p.validFrom<=filters.date&&!!p.validUntil&&p.validUntil>=filters.date))&&(!filters.cbm||!p.limits||((p.limits.minCbm===null||Number(filters.cbm)>=p.limits.minCbm)&&(p.limits.maxCbm===null||Number(filters.cbm)<=p.limits.maxCbm)))&&(!filters.kg||!p.limits||((p.limits.minKg===null||Number(filters.kg)>=p.limits.minKg)&&(p.limits.maxKg===null||Number(filters.kg)<=p.limits.maxKg))));
 return <div className="daily-prices"><Panel title="每日价格与运费"><p>全员查询同一云端版本。正式报价以签发时保存的价格依据为准，更新不会改动历史报价。</p><div className="price-tabs" role="tablist" aria-label="每日价格分类">{[['fx','今日汇率'],['freight','国际物流运费'],['product','产品销售价格']].map(([key,label])=><button role="tab" aria-selected={tab===key} className={tab===key?'primary':''} key={key} onClick={()=>{setTab(key);setSearch('');setStatus('');}}>{label}</button>)}</div><div className="price-statusbar"><span>云端定时：{o.config.enabled?'已启用':'已暂停'} · 北京时间 {o.config.times.join('、')}</span><span>最近检查：{time(o.lastChecked)}</span><span>最近同步新版本：{time(o.lastSuccess)}</span><span>下次执行：{o.config.enabled?time(o.nextRun):'已暂停'}</span></div>{o.lastError&&<ErrorBox message={`同步失败：${o.lastError}。下方保留上次成功数据，请同时检查有效期。`}/>}<div className="form-grid"><Field label="搜索"><input aria-label="搜索价格" placeholder={tab==='fx'?'USD、EUR、JPY 等币种':'型号、名称、航线或提供方'} value={search} onChange={e=>setSearch(e.target.value)}/></Field><Field label="状态筛选"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{['有效','待确认','已过期',...(tab==='fx'?['同步失败']:[])].map(s=><option key={s}>{s}</option>)}</select></Field></div></Panel>
 {tab==='fx'&&<><Panel title="市场参考汇率"><p>欧洲央行参考中间汇率，不是银行现汇买入价或卖出价。统一为 <b>1单位外币＝人民币</b>，交叉换算：来源CNY÷来源外币（来源基准1 EUR）。参考有效期为公司查询策略，并非银行承诺有效期。</p><p>来源只提供日期，不虚构发布时间；周末/假日显示最近一期。未接入币种：{o.missingCurrencies.join('、')||'当前查询币种均覆盖'}。搜索不到的币种表示未接入。</p><div className="price-table"><table><thead><tr><th>外币</th><th>人民币/1外币</th><th>汇率种类 / 来源</th><th>来源发布日期</th><th>首次同步该版本</th><th>参考有效至</th><th>状态</th></tr></thead><tbody>{o.reference.filter(r=>(!q||r.currency.toLowerCase().includes(q))&&(!status||r.status===status||(status==='同步失败'&&r.syncFailed))).map(r=><tr key={r.currency}><td>{r.currency}</td><td>{r.cnyPerUnit.toFixed(8)}</td><td>参考中间汇率<small><a href={r.sourceUrl} target="_blank" rel="noreferrer">{r.source}</a></small></td><td>{r.date}</td><td>{time(r.firstSyncedAt)}</td><td>{r.validUntil}</td><td><Badge s={r.status}/>{r.syncFailed&&<small><Badge s="同步失败"/> 沿用旧数据</small>}</td></tr>)}</tbody></table>{!o.reference.length&&<p className="price-empty">等待服务器首次同步；不会显示演示汇率。</p>}</div></Panel><Panel title="公司实际报价汇率"><p>当前策略：{o.config.mode==='manual'?'保留公司人工核准汇率':'管理员已选用ECB参考值并设置公司缓冲'}。CNY计价无需换汇。缓冲加在外币销售金额上，不改变市场参考值。</p><div className="price-table"><table><thead><tr><th>币种</th><th>人民币/1外币</th><th>销售金额缓冲</th><th>来源</th><th>数据日期</th><th>有效至</th><th>状态</th></tr></thead><tbody>{o.company.filter(r=>!q||r.currency.toLowerCase().includes(q)).map(r=><tr key={r.currency}><td>{r.currency}</td><td>{r.cnyPerUnit}</td><td>{r.bufferPct}%</td><td>{r.source}</td><td>{r.date}</td><td>{r.validUntil}</td><td><Badge s={r.status}/></td></tr>)}</tbody></table>{!o.company.length&&<p className="price-empty">尚无公司核准的外币报价汇率；市场参考不会自动成为正式报价汇率。</p>}</div></Panel></>}
 {tab==='product'&&<Panel title="产品销售价格"><p>标准配置价格均为人民币；尺寸、五金、玻璃、颜色、包装变化需要在报价管理重新计算。未核准的供应商导入不在此发布。</p><div className="price-table"><table><thead><tr><th>型号 / 产品</th><th>配置及尺寸</th><th>销售价格 / 单位</th><th>来源</th><th>来源发布 / 成功同步</th><th>有效期</th><th>状态</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.sku}<small>{p.name} · {p.category} · {p.series}</small></td><td>{Object.entries(p.specs).map(([k,v])=><small key={k}>{k}：{v}</small>)}<small>宽 {p.width.join('–')} mm / 高 {p.height.join('–')} mm</small><small>包装：{p.packing||'待确认'}</small></td><td>{p.sale===null?'待核价':`${p.sale} CNY`}<small>{unitNames[p.pricing]||p.pricing}</small>{p.options.map((opt,i)=><small key={i}>{opt.name}：{opt.sale??'待核价'}</small>)}</td><Provenance p={p}/></tr>)}</tbody></table>{!products.length&&<p className="price-empty">没有匹配的核准产品价目表，待工厂/公司提供真实资料后核价。</p>}</div><Link to="/quotations">进入报价管理选择产品</Link></Panel>}
 {tab==='freight'&&<Panel title="国际物流运费"><div className="form-grid">{Object.entries({country:'目的国家',city:'城市',origin:'起运港',destination:'目的港',container:'柜型',cbm:'体积m³',kg:'重量kg',date:'预计出运日期'}).map(([key,label])=><Field key={key} label={label}><input type={key==='date'?'date':['cbm','kg'].includes(key)?'number':'text'} min="0" step="any" value={filters[key as keyof typeof filters]} onChange={e=>setFilters(f=>({...f,[key]:e.target.value}))}/></Field>)}<Field label="运输方式"><select value={filters.mode} onChange={e=>setFilters(f=>({...f,mode:e.target.value}))}><option value="">全部</option>{[['LCL','拼箱'],['FCL','整柜'],['air','空运'],['courier','快递'],['rail','铁路'],['truck','陆运']].map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></Field></div><p>仅展示已核准货代报价；未接入航运指数或网络参考价。限制条件为空表示未提供，正式出运仍须货代确认。受限采购运费不直接展示，销售金额在报价计算后查看。</p><div className="price-table"><table><thead><tr><th>航线 / 方式</th><th>已确认费用（非空才计入）</th><th>包含 / 不包含</th><th>来源</th><th>来源发布 / 成功同步</th><th>有效期</th><th>状态</th></tr></thead><tbody>{freight.map(p=><tr key={p.id}><td>{p.originPort} → {p.country} {p.city} {p.destinationPort}<small>{p.name} · {p.mode} {p.container}</small><small>预计时效：{p.transitDays||'待确认'}</small></td><td>{p.fees.map((fee,i)=><small key={i}>{feeNames[fee.kind]}：{p.costRestricted?'按权限隐藏采购运价':fee.rate??'待询价'} {p.currency}/{unitNames[fee.basis]}{!p.costRestricted&&fee.minimum!==null?`（最低${fee.minimum}）`:''}</small>)}</td><td>含：{p.inclusions||'待确认'}<small>不含：{p.exclusions||'待确认'}</small></td><Provenance p={p}/></tr>)}</tbody></table>{!freight.length&&<p className="price-empty">待询价：没有满足该航线、出运日期和货物条件的货代报价。未知费用不会按0计入。</p>}</div></Panel>}
 {user.role==='admin'&&<><AdminSync key={o.configVersion} o={o}/><ImportPrices/><Panel title="最近云端运行 / 管理员提醒">{o.alerts.map(a=><ErrorBox key={a.id} message={a.message}/>)}<div className="price-table"><table><thead><tr><th>开始时间</th><th>触发</th><th>结果</th><th>尝试次数</th><th>说明</th></tr></thead><tbody>{o.runs.map(r=><tr key={r.id}><td>{time(r.started_at)}</td><td>{r.trigger==='manual'?'管理员':'云端定时'}</td><td>{{updated:'新版本已保存',unchanged:'检查成功，来源无新数据',failed:'同步失败',running:'运行中',interrupted:'中断后恢复'}[r.status]||r.status}</td><td>{r.attempts}</td><td>{r.error||'—'}</td></tr>)}</tbody></table></div></Panel></>}
 </div>;
}
function AdminSync({o}:{o:Overview}) {
 const {refresh,notify}=useSession(),m=useMutation(),[form,setForm]=useState(o.config),[times,setTimes]=useState(o.config.times.join(',')),[currencies,setCurrencies]=useState(o.config.currencies.join(',')),[ack,setAck]=useState(false);
 return <Panel title="管理员：自动更新与报价汇率"><form onSubmit={e=>{e.preventDefault();void m.run('/pricing/config','PUT',{version:o.configVersion,data:{...form,times:times.split(/[,，]/).map(s=>s.trim()),currencies:currencies.toUpperCase().split(/[,，]/).map(s=>s.trim())},acknowledgeReference:ack},()=>{refresh();notify('云端配置已保存，无需重启');});}}><div className="form-grid"><Field label="每天检查时间（北京时间，逗号分隔）"><input value={times} onChange={e=>setTimes(e.target.value)}/></Field><Field label="关注币种（逗号分隔）"><input value={currencies} onChange={e=>setCurrencies(e.target.value)}/></Field><Field label="参考数据有效天数（自来源日期起）"><input type="number" min="1" max="14" value={form.referenceDays} onChange={e=>setForm(f=>({...f,referenceDays:Number(e.target.value)}))}/></Field><Field label="公司报价汇率策略"><select value={form.mode} onChange={e=>setForm(f=>({...f,mode:e.target.value as PricingConfig['mode']}))}><option value="manual">保留原公司人工核准汇率</option><option value="ecb_reference">采用ECB参考汇率（仅所选币种）</option></select></Field><Field label="采用ECB时的销售金额缓冲%"><input type="number" min="0" max="20" step="0.01" value={form.bufferPct} onChange={e=>setForm(f=>({...f,bufferPct:Number(e.target.value)}))}/></Field></div><label><input type="checkbox" checked={form.enabled} onChange={e=>setForm(f=>({...f,enabled:e.target.checked}))}/>启用云端自动检查</label>{form.mode==='ecb_reference'&&<p><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>我确认使用参考汇率制定公司报价；这不是银行成交价，已核对缓冲和有效期。</label></p>}<p>默认07:30晨间检查，23:30补检查ECB工作日发布的数据。未出现新数据不会延长原有效期。</p><div className="actions"><button disabled={m.busy} className="primary">保存配置</button><button type="button" disabled={m.busy||o.running} onClick={()=>void m.run('/pricing/sync','POST',{},()=>{refresh();notify('已安排云端检查，请稍候查看运行记录');})}>{o.running?'同步中':'立即同步'}</button><Link to="/quotations/settings">管理员高级规则（原JSON）</Link></div><ErrorBox message={m.error}/></form></Panel>;
}
function ImportPrices() {
 const {revision,refresh,notify}=useSession(),m=useMutation(),[form,setForm]=useState({kind:'product',provider:'',sourceDate:'',validFrom:'',validUntil:''}),[file,setFile]=useState<File|null>(null),[note,setNote]=useState('');
 const list=useResource<{id:string;kind:string;name:string;provider:string;source_date:string;valid_from:string;valid_until:string;status:string;rows:Record<string,unknown>[];review_note:string}[]>('/pricing/imports',revision);
 async function upload(){if(!file)return;if(file.size>2*1024*1024){m.setError('文件不能超过2MB');return;}let binary='';for(const b of new Uint8Array(await file.arrayBuffer()))binary+=String.fromCharCode(b);await m.run('/pricing/imports','POST',{...form,name:file.name,data:btoa(binary)},()=>{refresh();notify('原始文件已保存，待管理员核对后发布');});}
 return <Panel title="管理员：工厂／货代真实价目表导入"><p>人工导入，不是自动货代接口。请下载空白CSV表头，用Excel填写后保存CSV或.xlsx。工厂底价不会自动成为销售价；变价一律待人工核对，批准时保留其他公司规则。</p><form onSubmit={e=>{e.preventDefault();void upload();}}><div className="form-grid"><Field label="资料类型"><select value={form.kind} onChange={e=>setForm(f=>({...f,kind:e.target.value}))}><option value="product">产品价目表</option><option value="freight">货代报价表</option></select></Field><Field label="真实提供方"><input required value={form.provider} onChange={e=>setForm(f=>({...f,provider:e.target.value}))}/></Field>{[['sourceDate','来源发布日期'],['validFrom','生效日期'],['validUntil','有效截止日']].map(([k,label])=><Field key={k} label={label}><input type="date" required value={form[k as keyof typeof form]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></Field>)}<Field label="原始文件（不超过2MB/500行）"><input type="file" accept=".csv,.xlsx" required onChange={e=>setFile(e.target.files?.[0]||null)}/></Field></div><p><a href={`/api/pricing/import-template/${form.kind}`}>下载空白导入表头</a></p>{form.kind==='freight'?<p>运输方式：LCL/FCL/air/courier/rail/truck。费用类型：domestic国内段、export出口港杂、international主运费、destination目的港杂、insurance保险、customs清关、duty税费、delivery派送、other其他。单位：fixed每票/cbm每立方米/kg每公斤/container每柜/chargeableKg计费公斤。同一报价编号每项费用一行；未确认金额留空，不能批准发布。</p>:<p>计价方式：area每平方米、unit每樘、piece每件、set每套、linear每米、area_options面积＋选项。币种仅CNY；其他币种供应商原价须先核算为公司销售价。复杂规格及包装重量规则继续在高级产品设置维护，缺项会阻止正式签发。</p>}<button className="primary" disabled={m.busy}>上传并等待核对</button></form><ErrorBox message={m.error||list.error}/><Field label="审核说明（批准前核对原文件、规格及异常变价；至少5字）"><input value={note} onChange={e=>setNote(e.target.value)}/></Field>{list.data?.map(b=><details key={b.id}><summary>{b.provider} · {b.name} · {b.rows.length}行 · {{pending:'待核对',approved:'已核准',rejected:'已驳回'}[b.status]}</summary><p>来源 {b.source_date} · 有效 {b.valid_from} 至 {b.valid_until} · <a href={`/api/pricing/imports/${b.id}/file`}>下载原始文件（仅管理员）</a></p><div className="price-table"><table><thead><tr>{Object.keys(b.rows[0]||{}).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{b.rows.slice(0,100).map((r,i)=><tr key={i}>{Object.keys(b.rows[0]||{}).map(k=><td key={k}>{String(r[k]??'待确认')}</td>)}</tr>)}</tbody></table></div>{b.rows.length>100&&<p>预览前100行，请下载原文件核对全部记录。</p>}{b.status==='pending'&&<div className="actions">{[true,false].map(approve=><button key={String(approve)} disabled={m.busy||note.trim().length<5} onClick={()=>void m.run(`/pricing/imports/${b.id}/review`,'POST',{approve,note},()=>{refresh();notify(approve?'已核准发布；草稿需重新核算':'已驳回，现有价格未改变');})}>{approve?'核对完成，批准发布':'驳回'}</button>)}</div>}<p>{b.review_note}</p></details>)}</Panel>;
}
