import { useState } from "react";
import { Link } from "react-router-dom";
import type { User } from "../../shared/contracts.ts";
import { useMutation,useResource } from "./api.ts";
import {useSession} from "./context.tsx";
import {ErrorBox,Field,Loading,Panel} from "./ui.tsx";
type Task={id:string;quote_id:string;project_id:string;name:string;number:number;discipline:string;status:string;version:number;assigned_to:string|null;comment:string};
type Detail=Task&{input:Record<string,unknown>;issues:{message:string;hard:boolean}[];lines:{key:string;sku:string;svg:string;specs:Record<string,string>}[];files:{id:string;name:string;kind:string}[];packing:{packages:number;cbm:number;grossKg:number;containers:string[]}};
export function QuoteTasks(){
  const{user,revision}=useSession(),tasks=useResource<Task[]>("/quoting/tasks",revision),[selected,setSelected]=useState("");
  if(user.role==="sales")return <ErrorBox message="销售无审批权限，请在报价项目查看审核进度"/>;
  return <><Panel title="报价审核与生产图纸任务"><p>技术、物流仅能处理管理员分配的任务。缺失价格/运价等硬性问题不能通过点“批准”跳过，需修正规则并新建报价版本。</p><ErrorBox message={tasks.error}/>{tasks.loading?<Loading/>:tasks.data?.map(t=><div key={t.id} className="quote-task"><b>{t.name} · V{t.number} · {t.discipline}</b> · {t.status} <button onClick={()=>setSelected(t.id)}>查看任务</button>{user.role==="admin"&&<Link to={`/quotations/${t.project_id}?v=${t.quote_id}`}>查看完整报价</Link>}</div>)}</Panel>{selected&&<TaskDetail key={`${selected}:${revision}`} taskId={selected}/>}</>;
}
function TaskDetail({taskId}:{taskId:string}){
  const{user,revision,refresh,notify}=useSession(),detail=useResource<Detail>(`/quoting/tasks/${taskId}`,revision),m=useMutation(),team=useResource<User[]>(user.role==="admin"?"/team":"/auth/owners");
  const[employee,setEmployee]=useState(""),[comment,setComment]=useState(""),[fileId,setFileId]=useState("");
  if(detail.loading)return <Loading/>;if(!detail.data)return <ErrorBox message={detail.error}/>;
  const t=detail.data;
  const upload=async(file:File)=>{if(file.size>2e6){notify("附件不能超过2MB");return;}let binary="";for(const b of new Uint8Array(await file.arrayBuffer()))binary+=String.fromCharCode(b);await m.run<{id:string}>(`/quoting/projects/${t.project_id}/files`,"POST",{name:file.name,mime:file.type,data:btoa(binary),kind:"technical",taskId},r=>{setFileId(r.id);notify("技术图纸已保存，请选择附件后完成审核");refresh();});};
  return <Panel title={`${t.discipline} 审核详情`}><p>项目：{String(t.input.name)} · {String(t.input.country)} · {String(t.input.incoterm)} · 发货 {String(t.input.targetDate)}</p><p>包装 {t.packing.packages} 件 / {t.packing.cbm} CBM / {t.packing.grossKg} kg</p><ul>{t.issues.map((i,n)=><li key={n}>{i.hard?"阻止出单":"审批项"}：{i.message}</li>)}</ul><div className="quote-drawings">{t.lines.map(l=><div key={l.key}><b>{l.sku}</b><div dangerouslySetInnerHTML={{__html:l.svg}}/><p>{Object.entries(l.specs).map(([k,v])=>`${k}: ${v}`).join(" · ")}</p></div>)}</div>{t.files.map(f=><p key={f.id}><a href={`/api/quoting/files/${f.id}?task=${taskId}`} target="_blank" rel="noreferrer">{f.name}</a></p>)}{t.status==="pending"&&<><div className="form-grid">{user.role==="admin"&&<Field label="分配员工"><select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">请选择</option>{team.data?.filter(u=>u.active&&(u.role==="admin"||u.role===(t.discipline==="production"?"technical":t.discipline))).map(u=><option key={u.id} value={u.id}>{u.name} · {u.role}</option>)}</select></Field>}{user.role==="admin"&&<button disabled={!employee||m.busy} onClick={()=>void m.run(`/quoting/tasks/${t.id}/assign`,"POST",{version:t.version,userId:employee},()=>{refresh();notify("已分配");})}>确认分配</button>}</div>{["technical","production"].includes(t.discipline)&&<><Field label="上传核实后的技术图纸（PDF/PNG/JPG）"><input type="file" disabled={m.busy} accept="application/pdf,image/png,image/jpeg" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/></Field><Field label="审核图纸附件"><select value={fileId} onChange={e=>setFileId(e.target.value)}><option value="">必须选择图纸</option>{t.files.filter(f=>f.kind==="technical").map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field></>}<Field label="审核意见 / 处理依据"><textarea value={comment} onChange={e=>setComment(e.target.value)}/></Field><div className="actions">{["approved","rejected"].map(status=><button key={status} disabled={m.busy||!comment.trim()} onClick={()=>void m.run(`/quoting/tasks/${t.id}/review`,"POST",{version:t.version,status,comment,fileId:fileId||null},()=>{refresh();notify("审核结果已记录");})}>{status==="approved"?"批准":"驳回"}</button>)}</div></>}<ErrorBox message={m.error}/></Panel>;
}
