import { useEffect, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import type { CustomerPage } from "../../shared/contracts.ts";
import { lineSchema, quoteInputSchema, specLabels, terms } from "../../shared/quoting.ts";
import type { Product, QuoteInput, QuoteLine, PublicCalculation, Freight } from "../../shared/quoting.ts";
import { api, useMutation, useResource } from "./api.ts";
import { useSession } from "./context.tsx";
import { Empty, ErrorBox, Field, Loading, Panel, Pagination } from "./ui.tsx";
type ProjectPage = { items: { id: string; name: string; company: string; status: string | null }[]; total: number };
type ProjectDetail = { project: { id: string; name: string; company: string; version: number }; versions: { id: string; number: number; status: string; reason: string; total: string | null; currency: string; created_at: string }[]; files: { id: string; name: string; kind: string }[]; order: { id: string } | null };
type Version = { id: string; number: number; version: number; status: string; input: QuoteInput; snapshot: PublicCalculation; reviews: { id: string; discipline: string; status: string; comment: string }[]; documents: { id: string; kind: string; language: string }[] };
const statusLabel: Record<string, string> = { draft: "草稿", submitted: "待审核", approved: "审核通过", issued: "已发布", confirmed: "已确认/订单", rejected: "驳回" };
const date = (n: number) => new Date(Date.now() + n * 864e5).toISOString().slice(0, 10);
function initial(name: string): QuoteInput { return quoteInputSchema.parse({ name, country: "待确认", currency: "CNY", incoterm: "EXW", targetDate: date(30), validUntil: date(14), lines: [lineSchema.parse({ key: "placeholder", productId: "00000000-0000-4000-8000-000000000000", width: 1200, height: 1500, quantity: 1 })] }); }
export function Quotations() {
  const { revision, refresh, notify } = useSession(), navigate = useNavigate(), m = useMutation();
  const [q, setQ] = useState(""), [page, setPage] = useState(1), [customerQuery, setCustomerQuery] = useState(""), [customerId, setCustomerId] = useState(""), [name, setName] = useState("");
  const projects = useResource<ProjectPage>(`/quoting/projects?page=${page}&q=${encodeURIComponent(q)}`, revision), customers = useResource<CustomerPage>(`/customers?page=1&q=${encodeURIComponent(customerQuery)}`, revision);
  return <><Panel title="奥汀堡海外产品出图报价系统"><p className="muted">选择客户 → 配置尺寸 → 服务端计价与运费 → 审批 → 报价PDF → 客户确认与订单</p><form onSubmit={e => { e.preventDefault(); void m.run<{ id: string }>("/quoting/projects", "POST", { customerId, name }, r => { refresh(); notify("项目已创建"); navigate(`/quotations/${r.id}`); }); }}><div className="form-grid"><Field label="查找客户"><input value={customerQuery} onChange={e => setCustomerQuery(e.target.value)} placeholder="公司、联系人或电话" /></Field><Field label="客户"><select required value={customerId} onChange={e => setCustomerId(e.target.value)}><option value="">请选择搜索结果</option>{customers.data?.items.map(c => <option key={c.id} value={c.id}>{c.company || c.contact}</option>)}</select></Field><Field label="项目名称"><input required maxLength={150} value={name} onChange={e => setName(e.target.value)} /></Field></div><ErrorBox message={m.error || customers.error} /><button className="primary" disabled={m.busy || !customerId}>创建报价项目</button></form></Panel><Panel title="报价项目"><Field label="搜索项目或客户"><input value={q} onChange={e => { setQ(e.target.value); setPage(1); }} /></Field><ErrorBox message={projects.error} />{projects.loading ? <Loading /> : projects.data?.items.length ? <><div className="quote-projects">{projects.data.items.map(p => <Link className="quote-project" key={p.id} to={`/quotations/${p.id}`}><strong>{p.name}</strong><span>{p.company}</span><small>{statusLabel[p.status || ""] || "尚无版本"} →</small></Link>)}</div><Pagination page={page} pages={Math.max(1, Math.ceil(projects.data.total / 20))} total={projects.data.total} onPage={setPage} /></> : <Empty text="暂无报价项目" />}</Panel></>;
}
export function QuoteProject() {
  const { id } = useParams(), { revision } = useSession(), [query, setQuery] = useSearchParams();
  const project = useResource<ProjectDetail>(`/quoting/projects/${id}`, revision), products = useResource<Product[]>("/quoting/products", revision), freight = useResource<Freight[]>(`/quoting/freight?project=${id}`, revision);
  if (project.loading || products.loading || freight.loading) return <Loading />;
  if (!project.data || !products.data || !freight.data) return <ErrorBox message={project.error || products.error || freight.error} />;
  const selected = query.get("v") || project.data.versions[0]?.id;
  return <><div className="quote-toolbar"><Link to="/quotations">← 报价项目</Link><b>{project.data.project.company} · {project.data.project.name}</b><select aria-label="历史报价版本" value={selected || ""} onChange={e => setQuery({ v: e.target.value })}><option value="">当前版本</option>{project.data.versions.map(v => <option key={v.id} value={v.id}>V{v.number} · {statusLabel[v.status]} · {v.currency} {v.total || "待核价"} · {v.reason}</option>)}</select></div>{selected ? <VersionLoader key={`${selected}:${revision}`} selected={selected} detail={project.data} products={products.data} freight={freight.data} /> : <QuoteEditor key={`new:${revision}`} detail={project.data} products={products.data} freight={freight.data} />}</>;
}
function VersionLoader(props: { selected: string; detail: ProjectDetail; products: Product[]; freight: Freight[] }) {
  const v = useResource<Version>(`/quoting/versions/${props.selected}`);
  if (v.loading) return <Loading />;
  return v.data ? <QuoteEditor {...props} saved={v.data} /> : <ErrorBox message={v.error} />;
}
function QuoteEditor({ detail, products, freight, saved }: { detail: ProjectDetail; products: Product[]; freight: Freight[]; saved?: Version }) {
  const { refresh, notify } = useSession(), [, setQuery] = useSearchParams(), m = useMutation(), workflow = useMutation();
const [form, setForm] = useState<QuoteInput>(() => saved?.input || { ...initial(detail.project.name), country: "", lines: [] }), [reason, setReason] = useState(saved ? "" : "首次报价"), [calculatedPreview, setPreview] = useState<PublicCalculation | null>(saved?.snapshot || null), [error, setError] = useState(""), [calculating, setCalculating] = useState(false), [catalogQ, setCatalogQ] = useState(""), [contact, setContact] = useState(""), [evidence, setEvidence] = useState(""), [kind, setKind] = useState("quotation"), [language, setLanguage] = useState("both"), [bundleName, setBundleName] = useState(""), [imported, setImported] = useState<{ lines: QuoteLine[]; errors: string[] } | null>(null);
  const bundles = useResource<{ id: string; name: string; lines: QuoteLine[] }[]>("/quoting/bundles"), [extraRevision, setExtraRevision] = useState(0);
  const frozen = !!detail.order, changed = JSON.stringify(form) !== JSON.stringify(saved?.input);
  const preview = !changed && saved ? saved.snapshot : calculatedPreview;
  useEffect(() => {
    let live = true;
    if (saved && JSON.stringify(form) === JSON.stringify(saved.input)) return;
    const timer = setTimeout(() => {
      const parsed = quoteInputSchema.safeParse(form);
      if (!parsed.success) { setPreview(null); setError("填写国家、有效日期和至少一个产品后可计算。"); return; }
      setCalculating(true); setError("");
      void api<PublicCalculation>(`/quoting/projects/${detail.project.id}/preview`, "POST", parsed.data).then(r => { if (live) setPreview(r); }).catch(e => { if (live) { setError(e.message); setPreview(null); } }).finally(() => { if (live) setCalculating(false); });
    }, 600);
    return () => { live = false; clearTimeout(timer); };
  }, [form, detail.project.id, saved]);
  const set = <K extends keyof QuoteInput>(k: K, v: QuoteInput[K]) => setForm(f => ({ ...f, [k]: v }));
  const updateLine = (index: number, line: QuoteLine) => setForm(f => ({ ...f, lines: f.lines.map((l, i) => i === index ? line : l) }));
  const add = (p: Product) => setForm(f => ({ ...f, lines: [...f.lines, lineSchema.parse({ key: crypto.randomUUID(), productId: p.id, width: 1200, height: 1500, quantity: 1, specs: p.standardSpecs, options: p.options.filter(o => o.required).map(o => o.id) })] }));
  async function upload(file: File, mode: "import" | "reference") {
    if (file.size > 2e6) { setError("文件不能超过2MB"); return; }
    const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; for (const b of bytes) binary += String.fromCharCode(b);
    if (mode === "import") await workflow.run<{ lines: QuoteLine[]; errors: string[] }>("/quoting/import-lines", "POST", { data: btoa(binary) }, setImported);
    else await workflow.run(`/quoting/projects/${detail.project.id}/files`, "POST", { name: file.name, mime: file.type, data: btoa(binary), kind: "reference" }, () => { notify("附件已保存；报价草稿仍在当前页面，请保存版本"); setExtraRevision(n => n + 1); });
  }
  const attachments = useResource<{ files: ProjectDetail["files"] }>(`/quoting/projects/${detail.project.id}`, extraRevision);
  return <><div className="quote-layout"><div><Panel title="1 · 项目信息"><fieldset disabled={frozen || m.busy} className="quote-fieldset"><div className="form-grid">{([['name','项目名称'],['country','国家'],['city','城市'],['projectAddress','项目地址'],['deliveryAddress','交货地址'],['originPort','起运港'],['destinationPort','目的港'],['namedPlace','贸易条款指定地点']] as const).map(([k,l]) => <Field key={k} label={l}><input value={form[k]} onChange={e => set(k,e.target.value)} /></Field>)}<Field label="币种"><input value={form.currency} maxLength={3} onChange={e => set("currency", e.target.value.toUpperCase())} placeholder="USD" /></Field><Field label="贸易条款"><select value={form.incoterm} onChange={e => set("incoterm",e.target.value as QuoteInput["incoterm"])}>{terms.map(t => <option key={t}>{t}</option>)}</select></Field><Field label="有效至"><input type="date" value={form.validUntil} onChange={e => set("validUntil",e.target.value)} /></Field><Field label="目标发货日期"><input type="date" value={form.targetDate} onChange={e => set("targetDate",e.target.value)} /></Field><Field label="付款条款"><textarea value={form.paymentTerms} onChange={e => set("paymentTerms",e.target.value)} /></Field><Field label="备注"><textarea value={form.notes} onChange={e => set("notes",e.target.value)} /></Field></div></fieldset></Panel>
    <Panel title="2 · 产品与参数"><fieldset disabled={frozen || m.busy} className="quote-fieldset"><Field label="搜索产品库"><input value={catalogQ} onChange={e => setCatalogQ(e.target.value)} /></Field><div className="quote-catalog">{products.filter(p => `${p.sku} ${p.nameZh} ${p.category}`.toLowerCase().includes(catalogQ.toLowerCase())).map(p => <button type="button" key={p.id} onClick={() => add(p)}>＋ {p.sku} · {p.nameZh}</button>)}</div>{!products.length && <p className="notice">产品库尚未配置，请管理员录入真实产品和价格。</p>}{form.lines.map((l,i) => <LineEditor key={l.key} line={l} product={products.find(p => p.id === l.productId)} index={i} set={v => updateLine(i,v)} duplicate={() => set("lines",[...form.lines,{...l,key:crypto.randomUUID()}])} remove={() => set("lines",form.lines.filter((_,n) => n !== i))} />)}<details><summary>Excel导入、常用组合与参考附件</summary><p>Excel导入仅加入配置，不接收成本或总价。请核对后再保存版本。</p><a href="/templates/quotation-lines.xlsx" download>下载Excel空白模板</a><Field label="导入产品明细 .xlsx"><input type="file" accept=".xlsx" disabled={workflow.busy} onChange={e => { const f = e.target.files?.[0]; if (f) void upload(f,"import"); e.target.value=""; }} /></Field>{imported && <div><ErrorBox message={imported.errors.join("；")} /><p>可导入 {imported.lines.length} 行</p><button type="button" disabled={!imported.lines.length || imported.errors.length > 0} onClick={() => { set("lines",[...form.lines,...imported.lines]); setImported(null); }}>确认加入明细</button></div>}<Field label="套用常用组合"><select defaultValue="" onChange={e => { const b = bundles.data?.find(b => b.id === e.target.value); if(b) set("lines",[...form.lines,...b.lines.map(l => ({...l,key:crypto.randomUUID()}))]); e.target.value=""; }}><option value="">请选择组合</option>{bundles.data?.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="保存组合名称"><input value={bundleName} onChange={e => setBundleName(e.target.value)} /></Field><button type="button" disabled={!bundleName || !form.lines.length || workflow.busy} onClick={() => void workflow.run("/quoting/bundles","POST",{name:bundleName,lines:form.lines},() => notify("组合已保存，重新进入页面可使用"))}>保存为常用组合</button><Field label="客户图纸或参考图（PDF/PNG/JPG，2MB）"><input type="file" accept="application/pdf,image/png,image/jpeg" disabled={workflow.busy} onChange={e => { const f = e.target.files?.[0]; if(f) void upload(f,"reference"); e.target.value=""; }} /></Field></details></fieldset>{attachments.data?.files.map(f => <p key={f.id}><a href={`/api/quoting/files/${f.id}`} target="_blank" rel="noreferrer">{f.name}</a></p>)}</Panel>
    <Panel title="3 · 物流与报价展示"><fieldset disabled={frozen || m.busy} className="quote-fieldset"><div className="form-grid"><Field label="运输方式"><select value={form.freightMode} onChange={e => set("freightMode",e.target.value as QuoteInput["freightMode"])}>{["LCL","FCL","air","courier","rail","truck","other"].map(t => <option key={t}>{t}</option>)}</select></Field><Field label="已核实运价"><select value={form.freightId || ""} onChange={e => set("freightId",e.target.value || null)}><option value="">未选择（EXW 可不选）</option>{freight.map(f => <option key={f.id} value={f.id}>{f.name} · {f.country} · {f.validUntil}</option>)}</select></Field><Field label="运费加价 %"><input type="number" min={0} max={100} value={form.freightMarkupPct} onChange={e => set("freightMarkupPct",Number(e.target.value))} /></Field><Field label="展示方式"><select value={form.freightDisplay} onChange={e => set("freightDisplay",e.target.value as QuoteInput["freightDisplay"])}><option value="separate">产品、包装、运费分列</option><option value="line">运费作为一行</option><option value="allocated">运费分摊产品</option><option value="total">仅展示总价</option></select></Field></div><label><input type="checkbox" checked={form.customerForwarder} onChange={e => set("customerForwarder",e.target.checked)} /> 客户指定货代（仍按贸易条款核算卖方费用）</label></fieldset></Panel></div>
    <aside className="quote-summary"><Panel title="服务端报价预览"><p className="muted">{calculating ? "正在重新计算…" : changed ? "当前输入尚未保存为版本" : "保存版本与当前输入一致"}</p><ErrorBox message={error || m.error || workflow.error} />{preview && <><div className="quote-total">{form.currency} {preview.total === null ? "待核价" : preview.total.toFixed(2)}</div><dl><dt>产品</dt><dd>{preview.productTotal.toFixed(2)}</dd><dt>包装</dt><dd>{preview.packingTotal.toFixed(2)}</dd><dt>运费</dt><dd>{preview.freightTotal?.toFixed(2) ?? "未核实"}</dd><dt>包装件数</dt><dd>{preview.packages}</dd><dt>体积</dt><dd>{preview.cbm} CBM</dd><dt>净重 / 毛重</dt><dd>{preview.netKg} / {preview.grossKg} kg</dd></dl>{preview.costs && <p>授权内部视图：成本 CNY {preview.costs.costCny} · 毛利 {preview.costs.marginPct}%</p>}<p className="muted">柜型初步建议：{preview.containers.join(" / ") || "无匹配，需物流核实"}。不代替装柜方案。</p><ul className="quote-issues">{preview.issues.map((i,n) => <li key={n}><b>{i.hard ? "阻止出单" : "需要审批"}</b> · {i.message}</li>)}</ul>{!preview.issues.length && <p className="success">规则校验通过，可保存并提交。</p>}</>}<Field label="本次版本变更原因"><input disabled={frozen} value={reason} onChange={e => setReason(e.target.value)} /></Field><button className="primary" disabled={frozen || m.busy || calculating || !reason.trim() || !form.lines.length} onClick={() => void m.run<{id:string}>(`/quoting/projects/${detail.project.id}/versions`,"POST",{baseVersion:detail.project.version,input:form,reason},r => {setQuery({v:r.id});refresh();notify("已保存新版本，旧版本保持不变");})}>{m.busy ? "保存中…" : saved ? "另存新报价版本" : "保存 V1 草稿"}</button>{frozen && <p>订单已确认。本项目只读，变更须新建项目。</p>}</Panel></aside></div>
    {preview && <Panel title="参数化报价示意图（非生产图纸）"><div className="quote-drawings">{preview.lines.map(l => <div key={l.key}><b>{l.sku} · {l.quantity} 件</b><div dangerouslySetInnerHTML={{__html:l.svg}} /></div>)}</div></Panel>}
    {saved && <Panel title={`保存版本 V${saved.number} · ${statusLabel[saved.status]}`}><p>以下操作只针对已保存版本。编辑后的参数须先另存新版本。</p><div className="actions">{saved.status === "draft" && <button disabled={workflow.busy || changed} onClick={() => void workflow.run(`/quoting/versions/${saved.id}/submit`,"POST",{version:saved.version},() => {refresh();notify("已提交审核");})}>提交审核</button>}{saved.status === "approved" && <button disabled={workflow.busy || changed} onClick={() => void workflow.run(`/quoting/versions/${saved.id}/issue`,"POST",{version:saved.version},() => {refresh();notify("正式报价已发布");})}>正式发布报价</button>}</div>{saved.reviews.map(r => <p key={r.id}>{r.discipline}：{r.status} · {r.comment}</p>)}{saved.status === "issued" && <div className="form-grid"><Field label="客户确认人"><input value={contact} onChange={e => setContact(e.target.value)} /></Field><Field label="确认凭据说明（至少10字，写明日期与沟通记录）"><textarea value={evidence} onChange={e => setEvidence(e.target.value)} /></Field><button disabled={workflow.busy || changed || !contact || evidence.length < 10} onClick={() => void workflow.run(`/quoting/versions/${saved.id}/confirm`,"POST",{version:saved.version,contact,evidence},() => {refresh();notify("已确认订单并创建生产图纸任务");})}>记录客户确认并转订单</button></div>}{detail.order && <p>订单号：SO-{detail.order.id.slice(0,8).toUpperCase()}。生产前必须完成技术图纸审核。</p>}{["issued","confirmed"].includes(saved.status) && <div className="quote-toolbar"><select aria-label="文件类型" value={kind} onChange={e => setKind(e.target.value)}><option value="quotation">报价单</option>{saved.status === "confirmed" && <><option value="pi">PI</option><option value="contract">合同（未核准模板时为草稿）</option></>}</select><select aria-label="文件语言" value={language} onChange={e => setLanguage(e.target.value)}><option value="both">中英双语</option><option value="en">英文</option><option value="zh">中文</option></select><button disabled={workflow.busy} onClick={() => void workflow.run(`/quoting/versions/${saved.id}/documents`,"POST",{kind,language},() => {refresh();notify("PDF已保存到数据库，可下载或打开打印");})}>{workflow.busy ? "生成中…" : "生成PDF"}</button></div>}{saved.documents.map(d => <p key={d.id}>{d.kind} · {d.language} <a href={`/api/quoting/documents/${d.id}`}>下载PDF</a> · <a href={`/api/quoting/documents/${d.id}?inline=1`} target="_blank" rel="noreferrer">打开 / 打印</a></p>)}<ErrorBox message={workflow.error} /></Panel>}</>;
}
function LineEditor({line:l,product:p,index,set,duplicate,remove}:{line:QuoteLine;product?:Product;index:number;set:(l:QuoteLine)=>void;duplicate:()=>void;remove:()=>void}) {
  const update = <K extends keyof QuoteLine>(k:K,v:QuoteLine[K]) => set({...l,[k]:v});
  const grid = (cols:number,rows:number) => set({...l,columns:cols,rows,panels:Array.from({length:Math.min(48,cols*rows)},(_,i)=>l.panels[i] || "fixed")});
  return <div className="quote-line"><div className="quote-toolbar"><b>{index+1} · {p?.sku || "产品已停用"} {p?.nameZh}</b><button type="button" onClick={duplicate}>复制产品</button><button type="button" onClick={remove}>移除</button></div><div className="form-grid">{([['width','宽度'],['height','高度'],['quantity','数量']] as const).map(([k,name])=><Field key={k} label={name}><input type="number" min={1} value={l[k]} onChange={e=>update(k,Number(e.target.value))}/></Field>)}<Field label="尺寸单位"><select value={l.unit} onChange={e=>update("unit",e.target.value as QuoteLine["unit"])}>{["mm","cm","m"].map(u=><option key={u}>{u}</option>)}</select></Field>{([['location','安装位置'],['floor','楼层'],['room','房间'],['openingNumber','洞口编号']] as const).map(([k,name])=><Field key={k} label={name}><input value={l[k]} onChange={e=>update(k,e.target.value)}/></Field>)}<Field label="横向分格"><input type="number" min={1} max={8} value={l.columns} onChange={e=>grid(Math.max(1,Math.min(8,Number(e.target.value))),l.rows)}/></Field><Field label="纵向分格"><input type="number" min={1} max={6} value={l.rows} onChange={e=>grid(l.columns,Math.max(1,Math.min(6,Number(e.target.value))))}/></Field><Field label="内开/外开"><select value={l.swing} onChange={e=>update("swing",e.target.value as QuoteLine["swing"])}><option value="in">内开</option><option value="out">外开</option></select></Field>{l.panels.map((v,i)=><Field key={i} label={`扇 ${i+1}（从室内看，左至右/上至下）`}><select value={v} onChange={e=>update("panels",l.panels.map((x,n)=>n===i?e.target.value as typeof x:x))}><option value="fixed">固定</option><option value="left">左向活动扇</option><option value="right">右向活动扇</option></select></Field>)}</div><div className="quote-options">{p?.options.map(o=><label key={o.id}><input type="checkbox" checked={l.options.includes(o.id)} onChange={e=>update("options",e.target.checked?[...l.options,o.id]:l.options.filter(v=>v!==o.id))}/> {o.group} · {o.nameZh} {o.required?"（必选）":""}</label>)}</div><details><summary>详细配置、性能要求和价格调整</summary><p className="muted">偏离产品标准参数将进入技术及价格审核。</p><div className="form-grid">{Object.entries(specLabels).map(([key,label])=><Field key={key} label={label}><input value={l.specs[key] || ""} onChange={e=>update("specs",{...l.specs,[key]:e.target.value})}/></Field>)}<Field label="特殊要求"><textarea value={l.special} onChange={e=>update("special",e.target.value)}/></Field><Field label="产品备注"><textarea value={l.notes} onChange={e=>update("notes",e.target.value)}/></Field><Field label="手动单价（报价币种，留空用规则）"><input type="number" min={0} step="0.01" value={l.unitPrice??""} onChange={e=>update("unitPrice",e.target.value===""?null:Number(e.target.value))}/></Field><Field label="折扣 %"><input type="number" min={0} max={100} value={l.discountPct} onChange={e=>update("discountPct",Number(e.target.value))}/></Field></div><label><input type="checkbox" checked={l.nonstandard} onChange={e=>update("nonstandard",e.target.checked)}/> 非标/异形，需技术出图</label></details></div>;
}
